### ISSUE TITLE
Feature Request: Proxy Support

### ISSUE THREAD

**Issue by Zeetaz** [m3n0sd0n4ld/GooFuzz#11]
Hello mate, noticed that this tool actually is included as the default for the OSINT section on reNgine 2.0 https://github.com/yogeshojha/rengine

However, that tool does not support any stand-alone rotating proxy features out of the box, instead it relies on tools having a proxy flag to easily utilized them. I'm just here to shamelessly ask if this is something that you would consider implementing?

`-proxy http://proxyIP:1234`

Essentially, I think this would be good enough(?):
- Add a new variable 'proxy' to store the proxy server's IP or hostname.
- Included the '-proxy' option to accept the proxy server's IP or hostname. (or whatever name)
- Modified the 'requestRun()' function to use the specified proxy server with the '-x' option in the curl command.

Other than that, the tool is great, cheers!

**Comment by Zeetaz** [comment]
Hmm, or perhaps this feature has been left out *intentionally*?

**Comment by m3n0sd0n4ld** [comment]
Hello,

Thank you for contacting me and letting me know that GooFuzz is included in reNgine 2.0, it is something I didn't know.

About your question, you can include it, as you say, curl has the "-x" option for it and you only have to include it.

And why doesn't it have it? Because it was never thought, since it is a tool that automates and facilitates the Google Dorking, so it made no sense to have it.

I will add it as an optional parameter, taking advantage of some new functionality/improvement of the tool, I can not tell you when it will be.

Thanks for writing, I will let you know when it is ready.

Best regards,

**Comment by m3n0sd0n4ld** [comment]
The option has been added in the new version of [GooFuzz v.1.2.5](https://github.com/m3n0sd0n4ld/GooFuzz/releases/tag/1.2.5).

Thanks for the suggestion.
