### ISSUE TITLE
Add 'sleep' at the end of any request

### ISSUE THREAD

**Issue by eitanshav** [m3n0sd0n4ld/GooFuzz#6]
Hi,

I think it will be a good idea to add some sleep between the requests to google because if your files list is big enough, google will block you or enforce you to solve a captcha (which you can't see  and therefore, you will get lots of FP results)

I've modified my code like this and it's work great!

function requestRun(){
        # Reset variables
        sleep 30
        requestStorage=""
        page=0

**Comment by m3n0sd0n4ld** [comment]
Hi,

Thanks for your input, yes I thought about the sleep, actually it was set in the development test but it blocked anyway, this is due to not only because of the limitation but because Google also analyzes what you search for and detects that they are "suspicious searches" and blocks immediately (even if it is the first or second request).

To avoid this as much as possible, the ideal is to have a VPN (if possible several) and as soon as you get the message "You are temporarily banned", deactivate the VPN and re-enable it.

For a use without VPN, you could add the sleep, but I would prefer to put it by a parameter so that the user knows that it will take 30 seconds (or the one specified) in each request. But as I said, if it is a "suspicious search" you will still get the captcha.

I note this option to implement it as a new optional parameter, thank you very much for your contribution!

Thank you very much for your contribution,

Greetings,

**Comment by m3n0sd0n4ld** [comment]
Sorry for the delay, but since I was making the modification, I added other improvements to the tool and today the new version is up and running!

Added "-d" (delay) parameter to add time between requests in GooFuzz 1.2.1 version.

Thanks for the input!
